services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: mydatabase

    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always

    ports:
      - "8888:8080"

    depends_on:
      - db

volumes:
  postgres_data: